id: 1373c248a475478bbf483d4c7612ba46
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_101-Upholding_the_Roots_of_Virtue-v2
  language: en
  author: ''
  volume: {}
